name: Cracker-RDP

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: curl.exe -o newt.exe -L "https://github.com/fosrl/newt/releases/download/1.6.0/newt_windows_amd64.exe"
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Run
      run: Start-Process .\newt.exe -ArgumentList "--id $Env:NEWT_ID --secret $Env:NEWT_SECRET --endpoint $Env:NEWT_ENDPOINT --accept-clients"
      env:
        NEWT_ENDPOINT: ${{ secrets.NEWT_ENDPOINT }}
      - NEWT_ID: ${{ secrets.NEWT_ID }}
      - NEWT_SECRET: ${{ secrets.NEWT_SECRET }}
    - name: sleep1
      run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - name: sleep2
      run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - name: sleep3
      run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
    - run: sleep 1000
